geocity/apps/accounts/urls.py
import logging

from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

logger = logging.getLogger(__name__)

app_name = "accounts"

urlpatterns = []

if settings.ENABLE_2FA:
    from two_factor.views import SetupCompleteView

    logger.info("2 factors authentification is enabled")
    urlpatterns += [
        path(
            "account/login/",
            views.CustomLoginView.as_view(template_name="two_factor/login.html"),
            name="account_login",
        ),
        path(
            "account/two_factor/",
            views.Custom2FAProfileView.as_view(
                template_name="two_factor/profile/profile.html"
            ),
            name="profile",
        ),
        path(
            "account/two_factor/setup/complete/",
            SetupCompleteView.as_view(
                template_name="two_factor/core/setup_complete.html"
            ),
            name="setup_complete",
        ),
    ]
else:
    logger.info("2 factors authentification is disabled")
    urlpatterns += [
        path(
            "account/login/",
            views.CustomLoginView.as_view(template_name="registration/login.html"),
            name="account_login",
        ),
    ]

urlpatterns += [
    path(
        "account/logout/",
        views.logout_view,
        name="logout",
    ),
    path(
        "account/lockout/",
        views.lockout_view,
        name="lockout",
    ),
    path(
        "account/password_reset/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "account/password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "account/activate/<uid>/<token>/",
        views.ActivateAccountView.as_view(),
        name="activate_account",
    ),
    path("profile/create/", views.user_profile_create, name="user_profile_create"),
    path("profile/edit/", views.user_profile_edit, name="user_profile_edit"),
    path(
        "admin-data/<path:path>",
        views.administrative_entity_file_download,
        name="administrative_entity_file_download",
    ),
    path(
        "custom-site-image/<path:path>",
        views.site_profile_custom_image,
        name="site_profile_custom_image",
    ),
]

geocity/apps/submissions/urls.py
from django.urls import include, path

from . import views
from .checklists.views import ChecklistUpdateView

app_name = "submissions"

submission_urlpatterns = [
    path(
        "administrative-entity/",
        views.submission_select_administrative_entity,
        name="submission_select_administrative_entity",
    ),
]

anonymous_submission_urlpatterns = [
    path(
        "anonymous/",
        views.anonymous_submission,
        name="anonymous_submission",
    ),
    path(
        "anonymous/sent",
        views.anonymous_submission_sent,
        name="anonymous_submission_sent",
    ),
]

existing_submission_urlpatterns = [
    path("", views.SubmissionDetailView.as_view(), name="submission_detail"),
    path(
        "objects/",
        views.submission_select_forms,
        name="submission_select_forms",
    ),
    path("properties/", views.submission_fields, name="submission_fields"),
    path("appendices/", views.submission_appendices, name="submission_appendices"),
    path("actors/", views.submission_contacts, name="submission_contacts"),
    path("submit/", views.submission_submit, name="submission_submit"),
    path("geotime/", views.submission_geo_time, name="submission_geo_time"),
    path("delete/", views.submission_delete, name="submission_delete"),
    path("approve/", views.submission_approve, name="submission_approve"),
    path("reject/", views.submission_reject, name="submission_reject"),
    path("cancel/", views.submission_cancel, name="submission_cancel"),
    path(
        "prolongation/",
        views.submission_prolongation,
        name="submission_prolongation",
    ),
    path(
        "service_fee/",
        views.submission_service_fees,
        name="create_submission_service_fees",
    ),
    path(
        "service_fee/<int:service_fee_id>/",
        views.submission_service_fees,
        name="submission_service_fees",
    ),
]

urlpatterns = [
    path(
        "<int:submission_id>/",
        include(submission_urlpatterns + existing_submission_urlpatterns),
    ),
    # TODO: adapt path name here and in front app
    path(
        "permits-files/<path:path>",
        views.submission_file_download,
        name="submission_file_download",
    ),
    path(
        "form-files/<path:path>",
        views.field_file_download,
        name="field_file_download",
    ),
    path(
        "documents/<path:path>/download",
        views.ComplementaryDocumentDownloadView.as_view(),
        name="complementary_documents_download",
    ),
    path(
        "documents/<int:pk>/delete",
        views.submission_complementary_document_delete,
        name="complementary_documents_delete",
    ),
    path("", views.SubmissionList.as_view(), name="submissions_list"),
    path("", include(submission_urlpatterns + anonymous_submission_urlpatterns)),
    path(
        "media/<int:property_value_id>/",
        views.submission_media_download,
        name="submission_media_download",
    ),
    path(
        "adminentitiesgeojson/<int:administrative_entity_id>/",
        views.administrative_entities_geojson,
        name="administrative_entities_geojson",
    ),
    path("search/", views.submissions_search, name="submissions_search"),
    path(
        "archives/",
        views.ArchivedSubmissionListView.as_view(),
        name="archived_submission_list",
    ),
    path(
        "archives/<int:pk>/delete",
        views.ArchivedSubmissionDeleteView.as_view(),
        name="archived_submission_delete",
    ),
    path(
        "archives/<int:pk>/download",
        views.ArchivedSubmissionDownloadView.as_view(),
        name="archived_submission_download",
    ),
    path(
        "archives/bulk-download",
        views.ArchivedSubmissionBulkDownloadView.as_view(),
        name="archived_submission_bulk_download",
    ),
    path(
        "transactions/<str:transaction_id>/change-status",
        views.ChangeTransactionStatus.as_view(),
        name="change_transaction_status",
    ),
    path(
        "transactions/confirm/<int:pk>",
        views.ConfirmTransactionCallback.as_view(),
        name="confirm_transaction",
    ),
    path(
        "transactions/confirm_prolongation/<int:pk>",
        views.ConfirmProlongationTransactionView.as_view(),
        name="confirm_prolongation_transaction",
    ),
    path(
        "transactions/fail_prolongation/<int:pk>",
        views.FailProlongationTransactionCallback.as_view(),
        name="fail_prolongation_transaction",
    ),
    path(
        "transactions/fail/<int:pk>",
        views.FailTransactionCallback.as_view(),
        name="fail_transaction",
    ),
    path(
        "payment/<int:pk>",
        views.SubmissionPaymentRedirect.as_view(),
        name="submission_payment_redirect",
    ),
    path(
        "validations/<int:submission_id>/edit",
        views.submission_validations_edit,
        name="submission_validations_edit",
    ),
    path(
        "validations/<int:validation_id>/return",
        views.ReturnValidationView.as_view(),
        name="submission_validations_return",
    ),
    path(
        "<int:submission_id>/checklist/<int:checklist_id>",
        ChecklistUpdateView.as_view(),
        name="checklist_update",
    ),
]

geocity/urls.py
import logging

from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.i18n import JavaScriptCatalog

import geocity.apps.api.urls
from geocity.apps.accounts.dootix.provider import DootixProvider
from geocity.apps.accounts.geomapfish.provider import GeomapfishProvider
from geocity.apps.django_wfs3.urls import wfs3_router
from geocity.apps.submissions import views as submissions_views

from .views import legacy_urls_redirect

logger = logging.getLogger(__name__)

# See TWO_FACTOR_PATCH_ADMIN
if settings.ENABLE_2FA:
    from .admin_site_2fa import AdminSiteOTPRequiredMixinRedirSetup

    admin.site = AdminSiteOTPRequiredMixinRedirSetup()


# Django-configuration
urlpatterns = [
    path("", submissions_views.submission_select_administrative_entity, name="index"),
    path("submissions/", include("geocity.apps.submissions.urls")),
    path("submissions/permits/", include("geocity.apps.permits.urls")),
    path("forms/", include("geocity.apps.forms.urls")),
    path("reports/", include("geocity.apps.reports.urls")),
    # Backward compatibility for Geocity < 2.1, will be deprecated in 3.0
    re_path(r"permit-requests/.*", legacy_urls_redirect),
]

# Append default urlpatterns for external providers
urlpatterns = (
    urlpatterns
    + default_urlpatterns(GeomapfishProvider)
    + default_urlpatterns(DootixProvider)
)


urlpatterns += [
    path("", include("geocity.apps.accounts.urls", namespace="accounts")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("rest/", include(geocity.apps.api.urls)),  # Django-rest urls
    path("wfs3/", include(wfs3_router.urls)),  # Django-rest urls
    path("captcha/", include("captcha.urls")),
    path("api-tokens/", include("knox.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("admin/", admin.site.urls),
    path("accounts/social/", include("allauth.socialaccount.urls")),
    path(
        "ckeditor5/", include("django_ckeditor_5.urls"), name="ck_editor_5_upload_file"
    ),
]

if settings.ENABLE_2FA:
    from two_factor.urls import urlpatterns as tf_urls

    urlpatterns += [
        path("", include(tf_urls)),
    ]

if settings.PREFIX_URL:
    urlpatterns = [path(settings.PREFIX_URL, include(urlpatterns))]

if settings.DEBUG:
    from django.views import defaults as default_views

    urlpatterns = [
        re_path(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission denied")},
        ),
        re_path(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        re_path(r"^500/$", default_views.server_error),
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns

geocity/apps/core/templates/_autosave-notifier.html
{% load i18n %}

<div id="global-autosave-notifier" class="autosave-notifier">
  {% include "_icon.html" with id="check" %}
  {% trans "Modifications sauvegardées" %}
</div>

geocity/apps/core/templates/_confirm-dialog.html
{% load i18n %}

<dialog id="confirmation-dialog" class="dialog dialog--sm" aria-labelledby="confirmation-dialog-title">
  <header class="dialog__header">
    <h1 id="confirmation-dialog-title" class="dialog__title">{% translate 'Avertissement' %}</h1>
    <button type="button" class="dialog__close-btn btn btn--icon" data-role="hide-dialog" data-dialog="confirmation-dialog" title="{% translate "Fermer la boîte de dialogue" %}" autofocus>
      {% include "_icon.html" with id="cross" %}
    </button>
  </header>

  <div id="confirmation-dialog-content" class="dialog__content"></div>

  <footer class="dialog__footer">
    <div class="form-actions form-actions--emphased mt-0">
      <button data-role="confirmation-confirm" type="button" class="btn btn--primary">
        {% translate 'Confirmer' %}
      </button>
      <span class="form-actions__spacer"></span>
      <button data-role="hide-dialog" data-dialog="confirmation-dialog" type="button" class="btn btn--default">
        {% translate 'Annuler' %}
      </button>
    </div>
  </footer>
</dialog>

geocity/apps/core/templates/_icon.html
{% load static %}

<svg class="icon icon--{{ id }}{% if class %} {{ class }}{% endif %}"{% if style %} style="{{ style }}"{% endif %} focusable="false" aria-hidden="true">
  <use xlink:href="{% block path %}{% static "images/icons.svg" %}{% endblock path %}#{{ id }}"></use>
</svg>

geocity/apps/core/templates/_phone-link.html
{% load core %}

{% if phone.is_valid %}
  <a href="{{ phone.as_rfc3966 }}"{% if title %} {{ title }}{% endif %}>{{ phone.as_international }}</a>
{% else %}
  {{ phone }}
{% endif %}

geocity/apps/core/templates/admin-geometry-widget.html
{% load i18n l10n %}

<div id="{{ id }}_div_map" class="dj_map_wrapper">
  {# RemovedInDjango51Warning: when the deprecation ends, remove data-width and data-height attributes. #}
  <div id="{{ id }}_map" class="dj_map" data-width="{{ map_width }}" data-height="{{ map_height }}"></div>

  {% if not disabled %}
    <div class="d-flex mt-2">
      <button id="{{ id }}_clear" type="button" class="btn btn-danger mr-2">{% translate "Delete all Features" %}</button>
      <label for="{{ id }}_klm" class="btn btn-default">{% translate 'Charger un fichier KML contenant un MultiPolygon' %}</label>
      <input type="file" id="{{ id }}_klm" class="sr-only">
    </div>
  {% endif %}

  {% if display_raw %}<p>{% translate "Debugging window (serialized value)" %}</p>{% endif %}
  <textarea id="{{ id }}" class="vSerializedField required" cols="150" rows="10" name="{{ name }}"
            {% if not display_raw %} hidden{% endif %}>{{ serialized }}</textarea>

  <script>
    {% block base_layer %}
      var base_layer = new ol.layer.Tile({source: new ol.source.OSM()});
    {% endblock %}

    {% block options %}
      var options = {
        base_layer: base_layer,
        geom_name: '{{ geom_type }}',
        id: '{{ id }}',
        map_id: '{{ id }}_map',
        map_srid: {{ map_srid|unlocalize }},
        name: '{{ name }}'
      };

      if (!document.getElementById('{{ id }}').value) {
        options['default_lon'] = 6.3;
        options['default_lat'] = 46.6;
        options['default_zoom'] = 7;
      }

    {% endblock %}

    var {{ module }} = new MapWidget(options);

    document.querySelector("#{{ id }}_clear").addEventListener("click", (e) => {
      e.preventDefault();
      {{ module }}.clearFeatures();
    });

    document.querySelector("#{{ id }}_klm").addEventListener("change", loadKML);

    function loadKML(e) {

      const filePicker = e.target;
      if (!filePicker) {
        return;
      }
      const file = filePicker.files[0];

      if (file) {
        var reader = new FileReader();
        reader.onloadend = () => {
          var kml = new ol.format.KML();
          var features = kml.readFeatures(reader.result);

          if (features.length > 50) {
            alert("Votre fichier dépasse la limite de 50 entités, il n’a pas été importé!");
          } else {
            for (var i = 0; i < features.length; i++) {

              var geomType = features[i].getGeometry().getType();
              if (geomType == "MultiPolygon") {
                var coord = features[i].getGeometry().getCoordinates();
                features[i].getGeometry().setCoordinates(coord, "XY");
                features[i].getGeometry().transform('EPSG:4326', 'EPSG:3857');

              } else {
                /*TODO: better info to the user...*/
                alert("Les géométries autres que MultiPolygon ne sont pas autorisées")
              }
            }
            {{ module }}.featureCollection.extend(features);
          }
        };
        reader.readAsText(file);
      }
    }
  </script>
</div>

geocity/apps/core/templates/base_generic.html
{% load core static i18n django_vite %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" class="antialiased">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="referrer" content="strict-origin-when-cross-origin">
    <title>{% block title %}{% endblock %}Geocity</title>
    <link rel="icon" href="{% static 'images/favicon.ico'%}" type="image/svg" sizes="16x16">

    {% block stylesheets %}{% endblock stylesheets %}

    <script src="{% static 'libs/js/jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% url 'javascript-catalog' %}" defer></script>
    {% vite_asset 'assets/js/common.js' %}
  </head>

  <body>
    <div class="master">
      {% block header %}
        <header class="sticky top-0 z-30 print:hidden">
          <div class="navbar">
            <div class="container content-center">
              <div class="flex items-center gap-4 md:gap-8">
                <div class="flex-shrink-0">
                  <a href="{% url 'submissions:submissions_list' %}">
                    <img src={% static 'images/geocity_normal.svg' %} alt="logo" width="147" height="29" class="h-4 lg:h-6 w-auto" />
                  </a>
                </div>

                {% if user.is_authenticated and not user.userprofile.is_temporary %}
                  <div class="flex-grow flex items-center gap-8">
                    <nav class="flex-grow max-md:hidden">
                      <ul class="flex gap-6">
                        <li>
                          <a href="{% url 'submissions:submissions_list' %}" class="btn navbar__btn{% highlight_menu_class 'submissions' 'permits' %}">
                            {% include "_icon.html" with id="list-todo" %}
                            {% translate "Mes demandes" %}
                          </a>
                        </li>

                        {% if config.GEOCALENDAR_URL %}
                          <li>
                            <a href="{{ config.GEOCALENDAR_URL }}" target="_blank" rel="noreferrer" class="btn navbar__btn">
                              {% include "_icon.html" with id="calendar-days" %}
                              {% translate "Calendrier" %}
                              {% include "_icon.html" with id="external-link" class="icon--75" %}
                            </a>
                          </li>
                        {% endif %}
                      </ul>
                    </nav>

                    <div class="ml-auto flex gap-6 items-center relative">
                      <button type="button" popovertarget="global-search-dropdown" class="btn navbar__btn" aria-label="Recherche">
                        {% include "_icon.html" with id="search" %}
                      </button>

                      <search id="global-search-dropdown" class="dropdown" data-popover-placement="bottom-end" popover>
                        <form method="get" action="{% url 'submissions:submissions_search' %}" data-role="global-search-form">
                          <div class="relative flex items-center my-2 mx-4">
                            <label for="global-search" class="sr-only">{% trans "Rechercher" %}</label>
                            <input id="global-search" data-role="search-input" placeholder="{% translate "Recherche…" %}" type="text" name="search" class="field h-10 pl-11 pr-5 rounded-full" autocomplete="off">
                            {% include "_icon.html" with id="search" class="absolute left-3 text-grey-300" %}
                          </div>
                          <div data-role="search-results" class="mt-2 hidden"></div>
                        </form>
                      </search>

                      <button type="button" popovertarget="user-menu" class="btn navbar__btn max-w-80{% highlight_menu_class 'accounts:user_profile_edit' 'two_factor:profile' 'two_factor:setup' 'accounts:profile' 'accounts:password_change' %}" title="{{ user.get_full_name }}">
                        {% include "_icon.html" with id="user" %}
                        <span class="overflow-hidden text-ellipsis max-md:sr-only">{{ user.get_full_name }}</span>
                        {% include "_icon.html" with id="chevron-down" class="icon--75 max-md:hidden" %}
                      </button>

                      <ul id="user-menu" class="dropdown" data-popover-placement="bottom-end" popover>
                        <li class="font-bold dropdown__item lg:hidden" aria-hidden="true">
                          {{ user.get_full_name }}
                        </li>
                        <hr class="dropdown__divider lg:hidden" aria-hidden="true">
                        {% if user.is_staff %}
                          <li>
                            <a href="{% url 'admin:index' %}" target="_blank" rel="noreferrer" class="btn dropdown__item">
                              {% translate "Interface d'administration" %}
                              {% include "_icon.html" with id="external-link" class="text-grey-500 icon--75" %}
                            </a>
                          </li>
                          <hr class="dropdown__divider">
                        {% endif %}

                        <li><a href="{% url 'accounts:user_profile_edit' %}" class="btn dropdown__item{% highlight_menu_class 'accounts:user_profile_edit' %}">{% translate "Gérer mon compte" %}</a></li>

                        {% if ENABLE_2FA %}
                          <li>
                            <a href="{% url 'two_factor:profile' %}" class="btn dropdown__item{% highlight_menu_class 'two_factor:profile' 'accounts:profile' 'two_factor:setup' %}">{% translate "Gérer la sécurité de mon compte" %}</a>
                          </li>
                        {% endif %}

                        {% if not user.socialaccount_set.exists %}
                          <li>
                            <a href="{% url 'accounts:password_change' %}" class="btn dropdown__item{% highlight_menu_class 'accounts:password_change' %}">{% translate "Modifier mon mot de passe" %}</a>
                          </li>
                        {% endif %}

                        <hr class="dropdown__divider">

                        <li>
                          <form method="post" action="{% url 'accounts:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn dropdown__item">
                              {% translate "Me déconnecter" %}
                            </button>
                          </form>
                        </li>
                      </ul>

                      <button type="button" class="btn navbar__btn lg:hidden" aria-label="Afficher le menu" popovertarget="mobile-menu">
                        {% include "_icon.html" with id="menu" %}
                      </button>
                    </div>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>

          <div id="mobile-menu" class="dropdown lg:hidden" data-popover-placement="bottom-end" popover>
            <nav>
              <ul class="grid gap-1">
                <li>
                  <a href="{% url 'submissions:submissions_list' %}" class="btn dropdown__item mobile-nav__btn{% highlight_menu_class 'submissions' 'permits' %}">
                    {% include "_icon.html" with id="list-todo" %}
                    {% translate "Mes demandes" %}
                  </a>
                </li>

                {% if config.GEOCALENDAR_URL %}
                  <li>
                    <a href="{{ config.GEOCALENDAR_URL }}" target="_blank" rel="noreferrer" class="btn dropdown__item mobile-nav__btn">
                      {% include "_icon.html" with id="calendar-days" %}
                      {% translate "Calendrier" %}
                      {% include "_icon.html" with id="external-link" class="icon--75" %}
                    </a>
                  </li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </header>
      {% endblock header %}

      <main class="main {% block main-class %}{% endblock main-class %}">
        <div id="global-toaster" class="toaster">
          {% for message in messages %}
            <div role="alert" class="alert
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert--danger
              {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}alert--success
              {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}alert--warning
              {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}alert--info{% endif %}
              ">{{ message }}</div>
          {% endfor %}
        </div>

        {% block content-wrapper %}
          {% block content %}{% endblock %}
        {% endblock content-wrapper %}
      </main>

      <footer class="py-6 text-grey-600 border-t border-grey-300 bg-grey-100 print:hidden">
        <div class="container">
          <div class="flex flex-wrap gap-5 items-center justify-between">
            &copy; {% now "Y" %} Geocity

            <div class="flex flex-wrap gap-x-6 gap-y-2 items-center">
              <a href="https://geocity-asso.ch" target="_blank" rel="noreferrer" class="btn btn--text">{% translate "A propos" %}</a>
              {% if config.CONTACT_URL %}
                <a href="{{ config.CONTACT_URL }}" target="_blank" rel="noreferrer" class="btn btn--text">{% translate "Contact" %}</a>
              {% endif %}
              {% if config.GENERAL_CONDITIONS_URL %}
                <a href="{{ config.GENERAL_CONDITIONS_URL }}" target="_blank" rel="noreferrer" class="btn btn--text" title="{% translate "Conditions générales d'utilisation" %}">{% translate "Conditions" %}</a>
              {% endif %}
              {% if config.PRIVACY_POLICY_URL %}
                <a href="{{ config.PRIVACY_POLICY_URL }}" target="_blank" rel="noreferrer" class="btn btn--text" title="{% translate "Politique de confidentialité" %}">{% translate "Confidentialité" %}</a>
              {% endif %}
              {% if config.LEGAL_NOTICE_URL %}
                <a href="{{ config.LEGAL_NOTICE_URL }}" target="_blank" rel="noreferrer" class="btn btn--text">{% translate "Mentions légales" %}</a>
              {% endif %}
            </div>
          </div>
        </div>
      </footer>
    </div>

    {% include "_confirm-dialog.html" %}

    {% block scripts %}{% endblock %}
  </body>
</html>