geocity/apps/submissions/urls.py
from django.urls import include, path

from . import views
from .checklists.views import ChecklistUpdateView

app_name = "submissions"

submission_urlpatterns = [
    path(
        "administrative-entity/",
        views.submission_select_administrative_entity,
        name="submission_select_administrative_entity",
    ),
]

anonymous_submission_urlpatterns = [
    path(
        "anonymous/",
        views.anonymous_submission,
        name="anonymous_submission",
    ),
    path(
        "anonymous/sent",
        views.anonymous_submission_sent,
        name="anonymous_submission_sent",
    ),
]

existing_submission_urlpatterns = [
    path("", views.SubmissionDetailView.as_view(), name="submission_detail"),
    path(
        "objects/",
        views.submission_select_forms,
        name="submission_select_forms",
    ),
    path("properties/", views.submission_fields, name="submission_fields"),
    path("appendices/", views.submission_appendices, name="submission_appendices"),
    path("actors/", views.submission_contacts, name="submission_contacts"),
    path("submit/", views.submission_submit, name="submission_submit"),
    path("geotime/", views.submission_geo_time, name="submission_geo_time"),
    path("delete/", views.submission_delete, name="submission_delete"),
    path("approve/", views.submission_approve, name="submission_approve"),
    path("reject/", views.submission_reject, name="submission_reject"),
    path("cancel/", views.submission_cancel, name="submission_cancel"),
    path(
        "prolongation/",
        views.submission_prolongation,
        name="submission_prolongation",
    ),
    path(
        "service_fee/",
        views.submission_service_fees,
        name="create_submission_service_fees",
    ),
    path(
        "service_fee/<int:service_fee_id>/",
        views.submission_service_fees,
        name="submission_service_fees",
    ),
]

urlpatterns = [
    path(
        "<int:submission_id>/",
        include(submission_urlpatterns + existing_submission_urlpatterns),
    ),
    # TODO: adapt path name here and in front app
    path(
        "permits-files/<path:path>",
        views.submission_file_download,
        name="submission_file_download",
    ),
    path(
        "form-files/<path:path>",
        views.field_file_download,
        name="field_file_download",
    ),
    path(
        "documents/<path:path>/download",
        views.ComplementaryDocumentDownloadView.as_view(),
        name="complementary_documents_download",
    ),
    path(
        "documents/<int:pk>/delete",
        views.submission_complementary_document_delete,
        name="complementary_documents_delete",
    ),
    path("", views.SubmissionList.as_view(), name="submissions_list"),
    path("", include(submission_urlpatterns + anonymous_submission_urlpatterns)),
    path(
        "media/<int:property_value_id>/",
        views.submission_media_download,
        name="submission_media_download",
    ),
    path(
        "adminentitiesgeojson/<int:administrative_entity_id>/",
        views.administrative_entities_geojson,
        name="administrative_entities_geojson",
    ),
    path("search/", views.submissions_search, name="submissions_search"),
    path(
        "archives/",
        views.ArchivedSubmissionListView.as_view(),
        name="archived_submission_list",
    ),
    path(
        "archives/<int:pk>/delete",
        views.ArchivedSubmissionDeleteView.as_view(),
        name="archived_submission_delete",
    ),
    path(
        "archives/<int:pk>/download",
        views.ArchivedSubmissionDownloadView.as_view(),
        name="archived_submission_download",
    ),
    path(
        "archives/bulk-download",
        views.ArchivedSubmissionBulkDownloadView.as_view(),
        name="archived_submission_bulk_download",
    ),
    path(
        "transactions/<str:transaction_id>/change-status",
        views.ChangeTransactionStatus.as_view(),
        name="change_transaction_status",
    ),
    path(
        "transactions/confirm/<int:pk>",
        views.ConfirmTransactionCallback.as_view(),
        name="confirm_transaction",
    ),
    path(
        "transactions/confirm_prolongation/<int:pk>",
        views.ConfirmProlongationTransactionView.as_view(),
        name="confirm_prolongation_transaction",
    ),
    path(
        "transactions/fail_prolongation/<int:pk>",
        views.FailProlongationTransactionCallback.as_view(),
        name="fail_prolongation_transaction",
    ),
    path(
        "transactions/fail/<int:pk>",
        views.FailTransactionCallback.as_view(),
        name="fail_transaction",
    ),
    path(
        "payment/<int:pk>",
        views.SubmissionPaymentRedirect.as_view(),
        name="submission_payment_redirect",
    ),
    path(
        "validations/<int:submission_id>/edit",
        views.submission_validations_edit,
        name="submission_validations_edit",
    ),
    path(
        "validations/<int:validation_id>/return",
        views.ReturnValidationView.as_view(),
        name="submission_validations_return",
    ),
    path(
        "<int:submission_id>/checklist/<int:checklist_id>",
        ChecklistUpdateView.as_view(),
        name="checklist_update",
    ),
]

geocity/urls.py
import logging

from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.i18n import JavaScriptCatalog

import geocity.apps.api.urls
from geocity.apps.accounts.dootix.provider import DootixProvider
from geocity.apps.accounts.geomapfish.provider import GeomapfishProvider
from geocity.apps.django_wfs3.urls import wfs3_router
from geocity.apps.submissions import views as submissions_views

from .views import legacy_urls_redirect

logger = logging.getLogger(__name__)

# See TWO_FACTOR_PATCH_ADMIN
if settings.ENABLE_2FA:
    from .admin_site_2fa import AdminSiteOTPRequiredMixinRedirSetup

    admin.site = AdminSiteOTPRequiredMixinRedirSetup()


# Django-configuration
urlpatterns = [
    path("", submissions_views.submission_select_administrative_entity, name="index"),
    path("submissions/", include("geocity.apps.submissions.urls")),
    path("submissions/permits/", include("geocity.apps.permits.urls")),
    path("forms/", include("geocity.apps.forms.urls")),
    path("reports/", include("geocity.apps.reports.urls")),
    # Backward compatibility for Geocity < 2.1, will be deprecated in 3.0
    re_path(r"permit-requests/.*", legacy_urls_redirect),
]

# Append default urlpatterns for external providers
urlpatterns = (
    urlpatterns
    + default_urlpatterns(GeomapfishProvider)
    + default_urlpatterns(DootixProvider)
)


urlpatterns += [
    path("", include("geocity.apps.accounts.urls", namespace="accounts")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("rest/", include(geocity.apps.api.urls)),  # Django-rest urls
    path("wfs3/", include(wfs3_router.urls)),  # Django-rest urls
    path("captcha/", include("captcha.urls")),
    path("api-tokens/", include("knox.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("admin/", admin.site.urls),
    path("accounts/social/", include("allauth.socialaccount.urls")),
    path(
        "ckeditor5/", include("django_ckeditor_5.urls"), name="ck_editor_5_upload_file"
    ),
]

if settings.ENABLE_2FA:
    from two_factor.urls import urlpatterns as tf_urls

    urlpatterns += [
        path("", include(tf_urls)),
    ]

if settings.PREFIX_URL:
    urlpatterns = [path(settings.PREFIX_URL, include(urlpatterns))]

if settings.DEBUG:
    from django.views import defaults as default_views

    urlpatterns = [
        re_path(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission denied")},
        ),
        re_path(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        re_path(r"^500/$", default_views.server_error),
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns

geocity/apps/submissions/checklists/models.py
from django.contrib.auth.models import Group
from django.db import models
from django.utils.translation import gettext_lazy as _


class Checklist(models.Model):
    """Checklist model"""

    name = models.CharField(max_length=255, null=False, blank=False)
    integrator = models.ForeignKey(
        Group,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("Groupe intégrateur"),
        limit_choices_to={"submission_department__is_integrator_admin": True},
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)


class ChecklistTask(models.Model):
    """Checklist Task model"""

    order = models.PositiveIntegerField(default=0)
    description = models.CharField(max_length=255, null=False, blank=False)
    checklist = models.ForeignKey(
        Checklist, related_name="tasks", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.order}"

    class Meta:
        ordering = ("order",)
        verbose_name = _("Tâche")
        verbose_name_plural = _("Tâches")


class SubmissionChecklist(models.Model):
    submission = models.ForeignKey(
        "submissions.PolymorphicSubmission",
        related_name="checklists",
        on_delete=models.CASCADE,
    )
    checklist = models.ForeignKey(
        Checklist, related_name="submission_checklists", on_delete=models.CASCADE
    )


class SubmissionChecklistTask(models.Model):
    submission_checklist = models.ForeignKey(
        SubmissionChecklist, related_name="tasks", on_delete=models.CASCADE
    )
    order = models.PositiveIntegerField()
    description = models.CharField(blank=True, max_length=255)
    completed = models.BooleanField(default=False)

    class Meta:
        ordering = ("order",)


class ChecklistForAdminSite(Checklist):
    class Meta:
        proxy = True
        app_label = "forms"
        verbose_name = _("1.10 Checklist")
        verbose_name_plural = _("1.10 Checklists")

geocity/apps/submissions/payments/postfinance/models.py
from simple_history.models import HistoricalRecords

from geocity.apps.submissions.payments.models import Transaction


class PostFinanceTransaction(Transaction):
    CHECKOUT_PROCESSOR_ID = "PostFinance"
    history = HistoricalRecords()

geocity/apps/submissions/checklists/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.views import View

from geocity.apps.permits.forms import ChecklistTasksForm
from geocity.apps.submissions.checklists.models import SubmissionChecklist
from geocity.apps.submissions.views import get_polymorphic_submission_for_edition


class ChecklistUpdateView(View):
    def post(self, request, submission_id, checklist_id, *args, **kwargs):
        poly_submission = get_polymorphic_submission_for_edition(
            request.user, submission_id
        ).get_specific()

        if not poly_submission.can_edit_submission(request.user):
            raise PermissionDenied

        submission_checklist = SubmissionChecklist.objects.get(pk=checklist_id)
        form = ChecklistTasksForm(submission_checklist, data=request.POST)
        if form.is_valid():
            for task in submission_checklist.tasks.all():
                task.completed = str(task.id) in form.cleaned_data["tasks"]
                task.save()
        return HttpResponse(status=204)

geocity/apps/submissions/templates/tables/_archived_submission_actions.html
{% load i18n submissions_extras %}

<div class="flex gap-3">
  {% can_download_archive as can_download %}
  {% if can_download %}
    <a title="{% translate 'Télécharger' %}" href="{% url 'submissions:archived_submission_download' record.pk %}" class="btn btn--text">
      {% include "_icon.html" with id="download" class="icon--75" %}
    </a>
  {% endif %}

  {% if record.archivist == request.user or request.user.is_superuser or can_download %}
    <a title="{% translate 'Supprimer' %}" href="{% url 'submissions:archived_submission_delete' record.pk %}" class="btn btn--text">
      {% include "_icon.html" with id="trash" class="icon--75" %}
    </a>
  {% endif %}
</div>

geocity/apps/submissions/templates/tables/_submission_actions.html
{% load i18n %}
{% load submissions_extras permits_extras %}

<div class="flex items-center gap-4">
  {% if record.permitsubmission %}
    {# TODO RESTRICTIONS TO VIEW A PERMIT REQUEST (NO ASSIGNATION) #}
    <a title="{% translate 'Voir' %}" href="{% url 'permits:permit_submission_detail:current' record.id %}" class="btn btn--icon">
      {% include "_icon.html" with id="eye" class="icon--75" %}
    </a>

    {# EDIT #}
    {% include "permits/_permit_submission_edit_btn.html" with submission=record %}

    {# DELETE #}
    {% if record.permitsubmission.author == request.user or request.user.is_superuser %}
      <a title="{% translate 'Supprimer' %}" href="{% url 'submissions:submission_delete' record.id %}" class="btn btn--icon">
        {% include "_icon.html" with id="trash" class="icon--75" %}
      </a>
    {% endif %}
  {% else %}
    {# VIEW #}
    {% if record.submission.author == request.user and not record.submission.can_be_edited_by_author or can_view %}
      {% if record.status is not 0 %}
        <a title="{% translate 'Voir' %}" href="{% url 'submissions:submission_detail' record.id %}" class="btn btn--icon">
          {% include "_icon.html" with id="eye" class="icon--75" %}
        </a>
      {% endif %}
    {% endif %}

    {# EDIT #}
    {% can_always_be_updated as can_update %}
    {% if record.submission.author == request.user and record.submission.can_be_edited_by_author or request.user.is_superuser or perms.submissions.edit_submission and record.submission.can_be_edited_by_pilot or can_update %}
      <a title="{% translate 'Modifier' %}" href="{% if record.submission.get_selected_forms %}{% url 'submissions:submission_fields' record.id %}{% else %}{% url 'submissions:submission_select_forms' record.id %}{% endif %}" class="btn btn--icon">
        {% include "_icon.html" with id="pencil" class="icon--75" %}
      </a>
    {% endif %}

    {# SEND #}
    {% if record.submission.author == request.user or request.user.is_superuser %}
      {% if record.submission.can_be_submitted_by_author %}
        <a title="{% translate 'Envoyer' %}" href="{% url 'submissions:submission_submit' record.id %}" class="btn btn--icon">
          {% include "_icon.html" with id="send" class="icon--75" %}
        </a>
      {% endif %}
    {% endif %}

    {# DELETE #}
    {% if record.submission.author == request.user or request.user.is_superuser %}
      {% if record.submission.can_be_deleted_by_author %}
        <a title="{% translate 'Supprimer' %}" href="{% url 'submissions:submission_delete' record.id %}" class="btn btn--icon">
          {% include "_icon.html" with id="trash" class="icon--75" %}
        </a>
      {% endif %}
    {% endif %}

    {# ASK DELAY #}
    {% if record.submission.can_be_prolonged %}
      {% if record.submission.can_prolongation_be_requested %}
        {% if record.submission.author == request.user %}
          <a title="{% translate 'Demander une prolongation' %}" href="{% url 'submissions:submission_prolongation' record.id %}" class="btn btn--icon">
            {% include "_icon.html" with id="clock" class="icon--75" %}
          </a>
        {% endif %}
      {% else %}
        {# This icons might as well be shown to other users #}
        {% if record.submission.prolongation_status == record.submission.PROLONGATION_STATUS_PENDING %}
          <div title="{% translate 'Prolongation en attente' %} ({{ record.submission.prolongation_date }})">
            {% include "_icon.html" with id="clock" class="icon--75 text-warning-500" %}
          </div>
        {% elif record.submission.prolongation_status == record.submission.PROLONGATION_STATUS_REJECTED %}
          <div title="{% translate 'Prolongation refusée' %}">
            {% include "_icon.html" with id="clock" class="icon--75 text-danger-500" %}
          </div>
        {% endif %}
      {% endif %}
    {% endif %}
  {% endif %}
</div>

geocity/apps/submissions/templates/tables/_submission_author_details.html
{% load i18n submissions_extras %}

{% comment %} Be careful with indentation and spaces, it influence the XLS export output {% endcomment %}
{% if not record.author.userprofile.is_temporary and not record.author.userprofile.is_anonymous %}
{{ record.author.email }}
{{ record.author.userprofile.phone_first }}
{{ record.author.userprofile.address }}
{{ record.author.userprofile.zipcode }} {{ record.author.userprofile.city }}
{% if record.author.userprofile.country %}{{ record.author.userprofile.country.name }}{% endif %}
{% else %}
—
{% endif %}

geocity/apps/submissions/templates/tables/_submission_author_fullname.html
{% load i18n %}
{% load submissions_extras %}

{% if record.is_permitsubmission or not record.submission.author.userprofile.is_temporary and not record.submission.author.userprofile.is_anonymous %}
  {{ record.requester }}
{% elif not record.author.userprofile.is_temporary and not record.author.userprofile.is_anonymous %}
  {% if record.author.userprofile.company_name %}
    {{ record.author.userprofile.company_name }}
  {% else %}
    {{ record.author.userprofile }}
  {% endif %}
{% else %}
  —
{% endif %}

geocity/apps/submissions/templates/tables/_submission_author_iban.html
{% load i18n %}
{% load submissions_extras %}

{% if not record.author.userprofile.is_temporary and not record.author.userprofile.is_anonymous and record.author.userprofile.iban %}
  {{ record.author.userprofile.iban }}
{% else %}
  —
{% endif %}

geocity/apps/submissions/templates/tables/_submission_ends_at.html
{% load i18n submissions_extras %}

<span class="text-nowrap">
  {% if record.prolongation_date and record.prolongation_status == record.PROLONGATION_STATUS_APPROVED %}
    {% if record.ends_at_max %}
      <del>{{ record.ends_at_max|date:"d.m.Y" }}</del><br>
    {% endif %}
    <ins>{{ record.prolongation_date|date:"d.m.Y" }}</ins>
  {% else %}
    {% if record.ends_at_max %}
      {{ record.ends_at_max|date:"d.m.Y" }}
    {% else %}
    —
    {% endif %}
  {% endif %}

  {% is_expired %}
</span>

geocity/apps/submissions/templates/tables/_submission_forms.html
{% load i18n %}

{% if record.is_submission and record.submission.forms %}
  {% regroup record.submission.forms.all by category as categories %}
  <div class="grid gap-2">
    {% for category in categories %}
      <div>
        <div class="text-xs text-grey-500">{{ category.grouper }}</div>

        {% for object in category.list %}
          <div>
            {% if record.submission.form_filter == object.id|stringformat:"i"  %}<mark>{% endif %}
              {{ object.name }}
            {% if record.submission.form_filter == object.id|stringformat:"i" %}</mark>{% endif %}
          </div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{% elif record.is_permitsubmission %}
  <div>
    <div class="text-xs text-grey-500">{% trans "Demande de permis de construire" %}</div>
    <div>{{ record.permitsubmission.submission_type_label }}</div>
  </div>
{% endif %}

geocity/apps/submissions/templates/tables/_submission_forms_str.html
{% regroup record.forms.all by category as categories %}

{% comment %} Be careful with indentation and spaces, it influence the XLS export output {% endcomment %}
{% for category in categories %}
{{ category.grouper }}: {% for object in category.list %}{{ object.name }}{% if not forloop.last %}, {% endif %}{% endfor %}{% endfor %}

geocity/apps/submissions/templates/tables/_submission_selected_price.html
{% load i18n %}
{% load submissions_extras %}

{% if record.get_submission_price %}
  {{ record.get_submission_price.text }} ({{ record.get_submission_price.amount }} {{ record.get_submission_price.currency }})
{% else %}
  —
{% endif %}

geocity/apps/submissions/templates/tables/_submission_service_fees_table_actions.html
{% load i18n submissions_extras %}

<div class="flex items-center gap-4">
  <a href="{% url 'submissions:submission_service_fees' submission_id=submission.pk service_fee_id=record.id %}?action=update" title="{% translate 'Modifier la prestation' %}" class="btn btn--icon">
      {% include "_icon.html" with id="pencil" class="icon--75" %}
  </a>
  <a href="{% url 'submissions:submission_service_fees' submission_id=submission.pk service_fee_id=record.id %}?action=delete" title="{% translate 'Supprimer la prestation' %}" class="btn btn--icon">
      {% include "_icon.html" with id="trash" class="icon--75" %}
  </a>
</div>

geocity/apps/submissions/templates/tables/_submission_status.html
{% include "submissions/_submission_status.html" with submission=record hightlight=True icon_class="icon--75" %}

geocity/apps/submissions/templates/tables/_submission_transactions_table_actions.html
{% load i18n %}
{% load submissions_extras %}

{% can_revert_refund_transaction as can_revert_refund %}
{% can_refund_transaction as can_refund %}

<div>{{ record.get_status_display }}</div>

{% if can_revert_refund or can_refund %}
  {% if record.status != 'failed' and record.can_have_status_changed %}
    <div class="mt-2 flex gap-3 items-center">
      <select class="field field--sm w-auto" id="payment-status-change-select-{{ record.transaction_id }}">
        <option value=""></option>
        {% if can_refund %}
          {% if record.status != 'to_refund' and record.status != 'refunded' and record.status != 'failed' %}
            <option value="to_refund">{% translate "À rembourser" %}</option>
          {% endif %}
          {% if record.status != 'refunded' and record.status != 'failed' %}
            <option value="refunded">{% translate "Remboursée" %}</option>
          {% endif %}
        {% endif %}
        {% if can_revert_refund and record.status != 'paid' and record.status != 'failed' %}
          <option value="paid">{% translate "Payée" %}</option>
        {% endif %}
      </select>

      <button class="btn btn--icon" data-role="change-payment-status" data-href="{% url 'submissions:change_transaction_status' record.transaction_id %}" data-merchant-reference="{{ record.transaction_id }}" title="{% translate "Sauvegarder" %}">
        {% include "_icon.html" with id="save" class="icon--75" %}
      </button>
    </div>
  {% endif %}
{% endif %}